% MATLAB Run Configurations
% @version 2
% It is recommended that you do not edit this file directly, but use the
% Configuration Editor provided in MATLAB. Changes made to comments that
% exist outside of a configuration will not be saved.

%% @name djema1
%  @associatedFile J:\djema1.m
%  @mostRecentlyActioned false
%  @uniqueId -5fa72c6c:13e9790f508:-7fec

% Modify expression to add input arguments.
% Example:
%   a = [1 2 3; 4 5 6]; 
%   foo(a);

djema1

